version: '2'

services:
    postgres:
        image: postgres:9.4
        env_file: ./config/env
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    backend:
        volumes:
            - ./backend:/home/blog/backend
        env_file: ./config/env
        build: ./backend
        working_dir: /home/blog/backend
        command: python3.5 manage.py runserver 0.0.0.0:8000
        container_name: backend
        depends_on:
          - postgres
        links:
           - postgres
        ports:
          - '8000:8000'

    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/home/blog/frontend
        container_name: frontend
        working_dir: /home/blog/frontend
        container_name: frontend        
        ports:
            - '80:80'
